export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Public} from './Public'
export {default as ForYou} from './ForYou'
export {default as ProductDetail} from './ProductDetail'
export {default as Product} from './Product'
export {default as ResetPassword} from './ResetPassword'